---
- name: '[cloudwatch-alarms] build lambda function'
  include_role:
    name: 'ringier.aws_cicd.build_lambda_function'
  vars:
    source_path: '{{ playbook_dir }}/../app/cloudwatch-alarms'

- name: '[cloudwatch-alarms] get CloudFormation template'
  set_fact:
    template_filename: '{{ role_path }}/files/cf-cloudwatch-alarms.yml'

- include_role:
    name: 'ringier.aws_cicd.run_cloudformation'
  vars:
    stack_name: '{{env}}-{{project_id}}-cloudwatch-alarms'
    template: '{{ template_filename }}'
