version: 0.2
env:
  variables:
    AGGRESSIVE_DEVELOPMENT: 1
phases:
  pre_build:
    commands:
      - ./ops-ci-shared/scripts/ci-init.sh
  build:
    commands:
      - ./ops-ci-shared/scripts/ci-test.sh app/cloudwatch-alarms
      - ./ops-ci-shared/scripts/ci-test.sh app/lambda-function-errors
      - ./ops-ci-shared/scripts/ci-deploy.sh
    finally:
      - ./ops-ci-shared/scripts/ci-notify-slack.sh
cache:
  paths:
    - '/root/.npm/**/*'
    - '/root/.ansible/**/*'
    - '/root/.cache/pip/**/*'
